<#
.SYNOPSIS
  ctx-kit -- install the embedding model that turns semantic_code_search from
  FTS5/BM25 keyword matching into actual vector search. Windows counterpart of
  install-model.sh.

.DESCRIPTION
  Separate from install.ps1 because it downloads ~80 MB and writes a
  machine-wide setting, which is a bigger commitment than the rest.

  What goes wrong without it, and why it is hard to notice: code-graph-mcp ships
  with vector search compiled in, but the weights download "lazily on first use".
  In practice that download can simply never fire -- `doctor` then reports "NO
  download has ever been attempted on this machine" forever, while
  semantic_code_search silently degrades to keyword matching and still returns
  plausible-looking results.

  Three traps this routes around:
    1. Hand-filling the DEFAULT cache dir (<cache>\code-graph\models) does NOT
       work. It is only trusted once the binary's own extract_and_promote has
       written a .model-id marker; a manually populated copy is ignored. The
       supported route is a SEPARATE dir pointed at by CODE_GRAPH_MODEL_DIR.
    2. The published .sha256 asset is a bare hash with no filename, so the usual
       checksum tools cannot parse it. It has to be compared by hand.
    3. Loading the model is not the same as using it. The server logs "Embedding
       model loaded successfully" while coverage stays at 0% -- embeddings are
       generated by an INDEX pass, so this script runs one. Re-run to resume.

.EXAMPLE
  .\install-model.ps1
.EXAMPLE
  .\install-model.ps1 -ProjectDir C:\src\myrepo -NoEmbed
#>
[CmdletBinding()]
param(
    [string]$ProjectDir,
    [string]$ModelDir = (Join-Path $env:USERPROFILE '.cache\code-graph\models-manual'),
    [switch]$NoEmbed
)

$KitDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $KitDir 'lib\common.ps1')

$ProjectDir = Resolve-ProjectDir $ProjectDir

Write-Step 'Preflight'
$CG = Resolve-CodeGraphBinary
if (-not $CG) { Stop-WithError 'code-graph-mcp not found -- run .\install.ps1 first' }

$versionOut = (& $CG --version 2>&1 | Out-String)
if ($versionOut -notmatch '(\d+\.\d+\.\d+)') { Stop-WithError 'could not determine code-graph-mcp version' }
$version = $Matches[1]
Write-Ok "code-graph-mcp v$version"

$modelFile = Join-Path $ModelDir 'model.safetensors'
if (Test-Path $modelFile) {
    Write-Ok "model already present at $ModelDir"
} else {
    Write-Step 'Download (~80 MB)'
    # Invoke-WebRequest in Windows PowerShell 5.1 paints a progress bar that
    # costs more wall-clock than the download itself on a large file, and
    # defaults to TLS 1.0/1.1 on older boxes, where GitHub simply closes the
    # connection.
    $ProgressPreference = 'SilentlyContinue'
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $base = "https://github.com/sdsrss/code-graph-mcp/releases/download/v$version"
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("ctx-kit-model-" + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    $archive = Join-Path $tmp 'models.tar.gz'
    try {
        try { Invoke-WebRequest -Uri "$base/models.tar.gz" -OutFile $archive -UseBasicParsing }
        catch { Stop-WithError "download failed: $base/models.tar.gz`n  $_" }
        # Downloaded to a FILE, not read from .Content: with -UseBasicParsing and
        # a non-text content type, .Content is a byte[]. Every string operator
        # then stringifies it element by element, and the comparison fails
        # against "57 52 98 52 ..." -- the right hash, printed as decimal bytes.
        $shaFile = Join-Path $tmp 'models.tar.gz.sha256'
        try { Invoke-WebRequest -Uri "$base/models.tar.gz.sha256" -OutFile $shaFile -UseBasicParsing }
        catch { Stop-WithError 'checksum download failed' }
        $expected = Get-Content $shaFile -Raw
        Write-Ok ("fetched {0:N1} MB" -f ((Get-Item $archive).Length / 1MB))

        # Trap 2: the asset is a bare hash, so no checksum tool can parse it.
        $expected = ($expected -replace '\s', '').ToLowerInvariant()
        $actual = (Get-FileHash -Path $archive -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($expected -ne $actual) {
            Stop-WithError "checksum mismatch -- refusing to install`n  expected: $expected`n  actual:   $actual"
        }
        Write-Ok 'checksum verified'

        # Trap 1: a separate dir, never the default cache dir.
        New-Item -ItemType Directory -Path $ModelDir -Force | Out-Null
        # bsdtar ships in System32 on Windows 10 1803+ and reads .tar.gz natively.
        $tarExe = Join-Path $env:SystemRoot 'System32\tar.exe'
        if (-not (Test-Path $tarExe)) { $tarExe = 'tar' }
        & $tarExe -xzf $archive -C $ModelDir
        if ($LASTEXITCODE -ne 0) { Stop-WithError 'tar extraction failed -- Windows 10 1803+ ships tar.exe in System32; on older builds extract the archive by hand' }
        if (-not (Test-Path $modelFile)) { Stop-WithError 'archive did not contain model.safetensors' }
        Write-Ok "extracted to $ModelDir"
    } finally {
        Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Write-Step 'Wire CODE_GRAPH_MODEL_DIR'
& node (Join-Path $KitDir 'lib\global-env.mjs') set CODE_GRAPH_MODEL_DIR $ModelDir | Out-Null
if ($LASTEXITCODE -eq 0) { Write-Ok 'CODE_GRAPH_MODEL_DIR set in ~\.claude\settings.json' }
else { Stop-WithError 'could not update ~\.claude\settings.json' }

if ($NoEmbed) {
    Write-Info 'skipped embedding pass (-NoEmbed)'
} else {
    Write-Step 'Generate embeddings'
    # Trap 3: loading the model is not enough -- coverage only moves during an
    # index pass. This walks every embeddable node, so it takes a few minutes on
    # a large repo and can be re-run to resume.
    Write-Info "indexing $ProjectDir -- a few minutes on a large repo, safe to re-run to resume"
    $env:CODE_GRAPH_MODEL_DIR = $ModelDir
    Push-Location $ProjectDir
    & $CG reindex *> $null
    $health = (& $CG health-check 2>&1 | Out-String)
    Pop-Location
    $status = ($health -split "`n" | Where-Object { $_ -match '(?i)^Search:' } | Select-Object -First 1)
    if ($status -match '(?i)hybrid') {
        Write-Ok $status.Trim()
        if ($status -match '(?i)in progress') { Write-Info 're-run this script to finish the remaining nodes' }
    } else {
        if ($status) { Write-Warn $status.Trim() } else { Write-Warn 'vector still inactive' }
    }
}

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green -NoNewline
Write-Host ' Restart Claude Code so the MCP server picks up CODE_GRAPH_MODEL_DIR.'
Write-Host 'Until then the CLI has the model but the running server does not.'
