#!/usr/bin/env bash
#
# ctx-kit — install the embedding model that turns semantic_code_search from
# FTS5/BM25 keyword matching into actual vector search.
#
#   ./install-model.sh [--project-dir DIR] [--no-embed]
#
# Why this is a separate script: it downloads ~80 MB and writes a machine-wide
# setting, which is a bigger commitment than the rest of the installer.
#
# ---------------------------------------------------------------------------
# What goes wrong without it, and why it is hard to notice
#
# code-graph-mcp ships with vector search compiled in, but the weights download
# "lazily on first use". In practice that download can simply never fire —
# `doctor` then reports "NO download has ever been attempted on this machine"
# forever, while semantic_code_search silently degrades to keyword matching and
# still returns plausible-looking results.
#
# Three traps this script exists to route around:
#
#   1. Hand-filling the DEFAULT cache dir (<cache>/code-graph/models) does NOT
#      work. That directory is only trusted once the binary's own
#      `extract_and_promote` has written a `.model-id` marker; a manually
#      populated copy is treated as not-current and ignored. The supported route
#      is a SEPARATE dir pointed at by CODE_GRAPH_MODEL_DIR.
#   2. The published `.sha256` asset is a bare hash with no filename, so
#      `shasum -c` fails with "no properly formatted SHA checksum lines found".
#      It has to be compared by hand.
#   3. Loading the model is not the same as using it. Starting the server logs
#      "Embedding model loaded successfully" while coverage stays at 0% —
#      embeddings are generated by an INDEX pass, so this script runs one.
# ---------------------------------------------------------------------------

KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$KIT_DIR/lib/common.sh"

MODEL_DIR="$HOME/.cache/code-graph/models-manual"
GLOBAL_SETTINGS="$HOME/.claude/settings.json"
PROJECT_DIR=""
DO_EMBED=1

while [ $# -gt 0 ]; do
  case "$1" in
    --project-dir) PROJECT_DIR="${2:?}"; shift 2 ;;
    --model-dir) MODEL_DIR="${2:?}"; shift 2 ;;
    --no-embed) DO_EMBED=0; shift ;;
    -h|--help)
      echo "usage: ./install-model.sh [--project-dir DIR] [--model-dir DIR] [--no-embed]"
      exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done
PROJECT_DIR="$(resolve_project_dir "${PROJECT_DIR:-$PWD}")"

step "Preflight"
require_cmd curl "needed to fetch the model"
CG="$(resolve_node_cli code-graph-mcp)" || die "code-graph-mcp not found — run ./install.sh first"
export PATH="$(dirname "$CG"):$PATH"

VERSION="$("$CG" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
[ -n "$VERSION" ] || die "could not determine code-graph-mcp version"
ok "code-graph-mcp v$VERSION"

if [ -f "$MODEL_DIR/model.safetensors" ]; then
  ok "model already present at $MODEL_DIR"
else
  step "Download (~80 MB)"
  BASE="https://github.com/sdsrss/code-graph-mcp/releases/download/v$VERSION"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT

  curl -fsSL -o "$TMP/models.tar.gz" "$BASE/models.tar.gz" \
    || die "download failed: $BASE/models.tar.gz"
  curl -fsSL -o "$TMP/models.tar.gz.sha256" "$BASE/models.tar.gz.sha256" \
    || die "checksum download failed"
  ok "fetched $(du -h "$TMP/models.tar.gz" | cut -f1)"

  # Trap 2: the asset is a bare hash, so `shasum -c` cannot parse it.
  EXPECTED="$(tr -d '[:space:]' < "$TMP/models.tar.gz.sha256")"
  if command -v shasum >/dev/null 2>&1; then
    ACTUAL="$(shasum -a 256 "$TMP/models.tar.gz" | awk '{print $1}')"
  else
    ACTUAL="$(sha256sum "$TMP/models.tar.gz" | awk '{print $1}')"
  fi
  [ "$EXPECTED" = "$ACTUAL" ] || die "checksum mismatch — refusing to install
  expected: $EXPECTED
  actual:   $ACTUAL"
  ok "checksum verified"

  # Trap 1: a separate dir, never the default cache dir.
  mkdir -p "$MODEL_DIR"
  tar -xzf "$TMP/models.tar.gz" -C "$MODEL_DIR"
  [ -f "$MODEL_DIR/model.safetensors" ] || die "archive did not contain model.safetensors"
  ok "extracted to $MODEL_DIR"
fi

step "Wire CODE_GRAPH_MODEL_DIR"
# Machine-wide, because the model is machine-wide and the MCP server inherits
# its environment from Claude Code. Merged, never clobbered.
if [ ! -f "$GLOBAL_SETTINGS" ]; then
  mkdir -p "$(dirname "$GLOBAL_SETTINGS")"
  printf '{}\n' > "$GLOBAL_SETTINGS"
fi
node -e '
  const fs = require("fs");
  const [file, dir] = process.argv.slice(1);
  let s = {};
  const raw = fs.readFileSync(file, "utf8").trim();
  if (raw) {
    try { s = JSON.parse(raw); }
    catch (e) {
      console.error("refusing to modify malformed JSON: " + file + "\n  " + e.message);
      process.exit(1);
    }
  }
  if (s.env && s.env.CODE_GRAPH_MODEL_DIR === dir) { console.log("unchanged"); process.exit(0); }
  s.env = { ...(s.env || {}), CODE_GRAPH_MODEL_DIR: dir };
  fs.writeFileSync(file, JSON.stringify(s, null, 2) + "\n");
  console.log("written");
' "$GLOBAL_SETTINGS" "$MODEL_DIR" >/dev/null \
  && ok "CODE_GRAPH_MODEL_DIR set in ~/.claude/settings.json" \
  || die "could not update $GLOBAL_SETTINGS"

if [ "$DO_EMBED" -eq 0 ]; then
  info "skipped embedding pass (--no-embed)"
else
  step "Generate embeddings"
  # Trap 3: the model loading is not enough — coverage only moves during an
  # index pass. This walks every embeddable node, so it takes a few minutes on a
  # large repo and can be re-run to resume.
  info "indexing $PROJECT_DIR — a few minutes on a large repo, safe to re-run to resume"
  ( cd "$PROJECT_DIR" && CODE_GRAPH_MODEL_DIR="$MODEL_DIR" "$CG" reindex ) >/dev/null 2>&1 || true
  status="$( cd "$PROJECT_DIR" && CODE_GRAPH_MODEL_DIR="$MODEL_DIR" "$CG" health-check 2>&1 | grep -i '^Search:' || true )"
  if printf '%s' "$status" | grep -qi 'hybrid'; then
    ok "$status"
    printf '%s' "$status" | grep -qi 'in progress' \
      && info "re-run this script (or ./install-model.sh --project-dir …) to finish the remaining nodes"
  else
    warn "${status:-vector still inactive}"
  fi
fi

cat <<EOF

${C_GRN}Done.${C_OFF} Restart Claude Code so the MCP server picks up CODE_GRAPH_MODEL_DIR.
Until then the CLI has the model but the running server does not.
EOF
